name: Test
on: [push, pull_request]
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16', '18' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
        working-directory: ./next-cloudinary
      - run: yarn test
        working-directory: ./next-cloudinary

